"""contracting core

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12 09:03:50.156675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Cerca difusa (trigram): la CI i les BD noves no executen ops/db-init.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contractors",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("tax_id", sa.String(length=20), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("company_type", sa.String(length=100), nullable=True),
        sa.Column("third_sector", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contractors")),
    )
    op.create_index(op.f("ix_contractors_tax_id"), "contractors", ["tax_id"], unique=False)
    op.create_table(
        "cpv_codes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("Division", "Group", "Class", "Category", name="cpv_level"),
            nullable=True,
        ),
        sa.Column("parent_code", sa.String(length=20), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cpv_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_cpv_codes_code")),
    )
    op.create_index(op.f("ix_cpv_codes_parent_code"), "cpv_codes", ["parent_code"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("contracts", "minor", "cpv", "extensions", "enrichment", name="sync_kind"),
            nullable=False,
        ),
        sa.Column(
            "trigger", sa.Enum("manual", "scheduled", "api", name="sync_trigger"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "success", "failed", "partial", name="sync_status"),
            server_default="running",
            nullable=False,
        ),
        sa.Column("new_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unchanged_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_source", sa.Integer(), nullable=True),
        sa.Column("endpoint", sa.String(length=500), nullable=True),
        sa.Column("error_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index(op.f("ix_sync_runs_kind"), "sync_runs", ["kind"], unique=False)
    op.create_index(op.f("ix_sync_runs_status"), "sync_runs", ["status"], unique=False)
    op.create_table(
        "association_rules",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("department_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("department", "body", "keyword", "cpv", "amount", name="rule_type"),
            nullable=False,
        ),
        sa.Column("source_field", sa.String(length=100), nullable=False),
        sa.Column("match_value", sa.String(length=500), nullable=False),
        sa.Column(
            "operator",
            sa.Enum("equals", "contains", "starts_with", "gt", "lt", name="rule_operator"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_association_rules_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_association_rules")),
    )
    op.create_index(
        op.f("ix_association_rules_department_id"),
        "association_rules",
        ["department_id"],
        unique=False,
    )
    op.create_table(
        "contractor_aliases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("contractor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractors.id"],
            name=op.f("fk_contractor_aliases_contractor_id_contractors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contractor_aliases")),
        sa.UniqueConstraint("alias", name=op.f("uq_contractor_aliases_alias")),
    )
    op.create_index(
        op.f("ix_contractor_aliases_contractor_id"),
        "contractor_aliases",
        ["contractor_id"],
        unique=False,
    )
    op.create_table(
        "contractor_duplicates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contractor_id_1", sa.BigInteger(), nullable=False),
        sa.Column("contractor_id_2", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "merged", "rejected", name="contractor_duplicate_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id_1"],
            ["contractors.id"],
            name=op.f("fk_contractor_duplicates_contractor_id_1_contractors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id_2"],
            ["contractors.id"],
            name=op.f("fk_contractor_duplicates_contractor_id_2_contractors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_contractor_duplicates_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contractor_duplicates")),
        sa.UniqueConstraint(
            "contractor_id_1", "contractor_id_2", name="uq_contractor_duplicates_pair"
        ),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("file_code", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("lot", sa.String(length=50), server_default="", nullable=False),
        sa.Column(
            "source",
            sa.Enum("local", "external", name="contract_source"),
            server_default="external",
            nullable=False,
        ),
        sa.Column("gestiona_file_id", sa.String(length=100), nullable=True),
        sa.Column("ine10_code", sa.String(length=10), nullable=True),
        sa.Column("dir3_code", sa.String(length=20), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("contract_type", sa.String(length=100), nullable=True),
        sa.Column("procedure", sa.String(length=100), nullable=True),
        sa.Column("processing_type", sa.String(length=100), nullable=True),
        sa.Column("contractor_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_contractor_name", sa.String(length=500), nullable=True),
        sa.Column("tender_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("award_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("award_amount_vat", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("budget_no_vat", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("budget_vat", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("formalized_at", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("calculated_end_date", sa.Date(), nullable=True),
        sa.Column("prior_notice_date", sa.Date(), nullable=True),
        sa.Column("tender_notice_date", sa.Date(), nullable=True),
        sa.Column("award_notice_date", sa.Date(), nullable=True),
        sa.Column("formalization_notice_date", sa.Date(), nullable=True),
        sa.Column("cancellation_date", sa.Date(), nullable=True),
        sa.Column("duration_months", sa.Integer(), nullable=True),
        sa.Column("expiry_warning", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("possibly_finished", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("warning_months_override", sa.Integer(), nullable=True),
        sa.Column("cpv_code", sa.String(length=20), nullable=True),
        sa.Column("cpv_description", sa.Text(), nullable=True),
        sa.Column("nuts_code", sa.String(length=10), nullable=True),
        sa.Column("nuts_description", sa.String(length=255), nullable=True),
        sa.Column("financing", sa.String(length=255), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("phase_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enrichment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("received_offers", sa.Integer(), nullable=True),
        sa.Column("is_harmonized", sa.Boolean(), nullable=True),
        sa.Column("allows_extensions", sa.Boolean(), nullable=True),
        sa.Column("allows_modifications", sa.Boolean(), nullable=True),
        sa.Column("social_reserve", sa.Boolean(), nullable=True),
        sa.Column("subcontracting_allowed", sa.Boolean(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "internal_status",
            sa.Enum("normal", "pending_review", "approved", "rejected", name="internal_status"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("first_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractors.id"],
            name=op.f("fk_contracts_contractor_id_contractors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("file_code", "status", "lot", name="uq_contracts_natural_key"),
    )
    op.create_index(
        op.f("ix_contracts_calculated_end_date"), "contracts", ["calculated_end_date"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_contractor_id"), "contracts", ["contractor_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_cpv_code"), "contracts", ["cpv_code"], unique=False)
    op.create_index(op.f("ix_contracts_file_code"), "contracts", ["file_code"], unique=False)
    op.create_index(
        op.f("ix_contracts_internal_status"), "contracts", ["internal_status"], unique=False
    )
    op.create_index(op.f("ix_contracts_source"), "contracts", ["source"], unique=False)
    op.create_index(op.f("ix_contracts_start_date"), "contracts", ["start_date"], unique=False)
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    op.create_table(
        "minor_contracts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("file_code", sa.String(length=100), nullable=False),
        sa.Column("contract_type", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contractor_id", sa.BigInteger(), nullable=True),
        sa.Column("award_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("award_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("duration_years", sa.Integer(), nullable=True),
        sa.Column("duration_months", sa.Integer(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("settlement_type", sa.String(length=100), nullable=True),
        sa.Column("settlement_date", sa.Date(), nullable=True),
        sa.Column("settlement_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "internal_status",
            sa.Enum("normal", "pending_review", "approved", "rejected", name="internal_status"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("raw_award", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_settlement", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractors.id"],
            name=op.f("fk_minor_contracts_contractor_id_contractors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_minor_contracts")),
        sa.UniqueConstraint("file_code", name=op.f("uq_minor_contracts_file_code")),
    )
    op.create_index(
        op.f("ix_minor_contracts_award_date"), "minor_contracts", ["award_date"], unique=False
    )
    op.create_index(
        op.f("ix_minor_contracts_contractor_id"), "minor_contracts", ["contractor_id"], unique=False
    )
    op.create_index(
        op.f("ix_minor_contracts_fiscal_year"), "minor_contracts", ["fiscal_year"], unique=False
    )
    op.create_index(
        op.f("ix_minor_contracts_internal_status"),
        "minor_contracts",
        ["internal_status"],
        unique=False,
    )
    op.create_table(
        "sync_item_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sync_run_id", sa.BigInteger(), nullable=False),
        sa.Column("file_code", sa.String(length=100), nullable=True),
        sa.Column("outcome", sa.String(length=100), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_sync_item_logs_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_item_logs")),
    )
    op.create_index(
        op.f("ix_sync_item_logs_sync_run_id"), "sync_item_logs", ["sync_run_id"], unique=False
    )
    op.create_table(
        "award_criteria",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_award_criteria_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_award_criteria")),
    )
    op.create_index(
        op.f("ix_award_criteria_contract_id"), "award_criteria", ["contract_id"], unique=False
    )
    op.create_table(
        "committee_members",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_committee_members_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_members")),
    )
    op.create_index(
        op.f("ix_committee_members_contract_id"), "committee_members", ["contract_id"], unique=False
    )
    op.create_table(
        "contract_departments",
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("department_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_departments_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_contract_departments_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "contract_id", "department_id", name=op.f("pk_contract_departments")
        ),
    )
    op.create_table(
        "contract_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum("sync", "manual", "validation", "gestiona_webhook", name="change_type"),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_history_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_contract_history_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_history")),
    )
    op.create_index(
        op.f("ix_contract_history_changed_at"), "contract_history", ["changed_at"], unique=False
    )
    op.create_index(
        op.f("ix_contract_history_contract_id"), "contract_history", ["contract_id"], unique=False
    )
    op.create_table(
        "contract_managers",
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_managers_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_contract_managers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("contract_id", "user_id", name=op.f("pk_contract_managers")),
    )
    op.create_table(
        "duplicates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id_1", sa.BigInteger(), nullable=False),
        sa.Column("contract_id_2", sa.BigInteger(), nullable=False),
        sa.Column("matched_on", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "merged", name="duplicate_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("action_taken", sa.String(length=255), nullable=True),
        sa.Column("validated_by", sa.BigInteger(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contract_id_1 < contract_id_2", name=op.f("ck_duplicates_pair_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["contract_id_1"],
            ["contracts.id"],
            name=op.f("fk_duplicates_contract_id_1_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contract_id_2"],
            ["contracts.id"],
            name=op.f("fk_duplicates_contract_id_2_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"],
            ["users.id"],
            name=op.f("fk_duplicates_validated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicates")),
        sa.UniqueConstraint("contract_id_1", "contract_id_2", name="uq_duplicates_pair"),
    )
    op.create_index(op.f("ix_duplicates_status"), "duplicates", ["status"], unique=False)
    op.create_table(
        "extensions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_extensions_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extensions")),
        sa.UniqueConstraint("contract_id", "number", name="uq_extensions_contract_id"),
    )
    op.create_index(op.f("ix_extensions_contract_id"), "extensions", ["contract_id"], unique=False)
    op.create_table(
        "minor_contract_departments",
        sa.Column("minor_contract_id", sa.BigInteger(), nullable=False),
        sa.Column("department_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_minor_contract_departments_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["minor_contract_id"],
            ["minor_contracts.id"],
            name=op.f("fk_minor_contract_departments_minor_contract_id_minor_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "minor_contract_id", "department_id", name=op.f("pk_minor_contract_departments")
        ),
    )
    op.create_table(
        "modifications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.Date(), nullable=True),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("term_years", sa.Integer(), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("term_days", sa.Integer(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_modifications_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifications")),
        sa.UniqueConstraint("contract_id", "number", name="uq_modifications_contract_id"),
    )
    op.create_index(
        op.f("ix_modifications_contract_id"), "modifications", ["contract_id"], unique=False
    )
    op.create_table(
        "phase_documents",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "futura",
                "agregada",
                "cpm",
                "previ",
                "licitacio",
                "avaluacio",
                "adjudicacio",
                "formalitzacio",
                "anulacio",
                name="contract_phase",
            ),
            nullable=False,
        ),
        sa.Column("doc_type", sa.String(length=100), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("source_doc_id", sa.String(length=200), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("download_url", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_phase_documents_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phase_documents")),
    )
    op.create_index(
        op.f("ix_phase_documents_contract_id"), "phase_documents", ["contract_id"], unique=False
    )

    # Índexs que el model no declara (docs/04-model-de-dades.md §2):
    # GIN sobre el payload cru i trigram per a cerca difusa de l'objecte.
    op.execute("CREATE INDEX ix_contracts_raw_gin ON contracts USING gin (raw)")
    op.execute(
        "CREATE INDEX ix_contracts_subject_trgm ON contracts USING gin (subject gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_cpv_codes_description_trgm ON cpv_codes "
        "USING gin (description gin_trgm_ops)"
    )

    # Trigger updated_at a totes les taules noves editables (contract_history
    # és un registre: no s'edita mai).
    for table in (
        "contractors",
        "contractor_aliases",
        "contractor_duplicates",
        "contracts",
        "extensions",
        "modifications",
        "award_criteria",
        "committee_members",
        "phase_documents",
        "duplicates",
        "association_rules",
        "minor_contracts",
        "sync_runs",
        "sync_item_logs",
        "cpv_codes",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phase_documents_contract_id"), table_name="phase_documents")
    op.drop_table("phase_documents")
    op.drop_index(op.f("ix_modifications_contract_id"), table_name="modifications")
    op.drop_table("modifications")
    op.drop_table("minor_contract_departments")
    op.drop_index(op.f("ix_extensions_contract_id"), table_name="extensions")
    op.drop_table("extensions")
    op.drop_index(op.f("ix_duplicates_status"), table_name="duplicates")
    op.drop_table("duplicates")
    op.drop_table("contract_managers")
    op.drop_index(op.f("ix_contract_history_contract_id"), table_name="contract_history")
    op.drop_index(op.f("ix_contract_history_changed_at"), table_name="contract_history")
    op.drop_table("contract_history")
    op.drop_table("contract_departments")
    op.drop_index(op.f("ix_committee_members_contract_id"), table_name="committee_members")
    op.drop_table("committee_members")
    op.drop_index(op.f("ix_award_criteria_contract_id"), table_name="award_criteria")
    op.drop_table("award_criteria")
    op.drop_index(op.f("ix_sync_item_logs_sync_run_id"), table_name="sync_item_logs")
    op.drop_table("sync_item_logs")
    op.drop_index(op.f("ix_minor_contracts_internal_status"), table_name="minor_contracts")
    op.drop_index(op.f("ix_minor_contracts_fiscal_year"), table_name="minor_contracts")
    op.drop_index(op.f("ix_minor_contracts_contractor_id"), table_name="minor_contracts")
    op.drop_index(op.f("ix_minor_contracts_award_date"), table_name="minor_contracts")
    op.drop_table("minor_contracts")
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_start_date"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_source"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_internal_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_file_code"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_cpv_code"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contractor_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_calculated_end_date"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_table("contractor_duplicates")
    op.drop_index(op.f("ix_contractor_aliases_contractor_id"), table_name="contractor_aliases")
    op.drop_table("contractor_aliases")
    op.drop_index(op.f("ix_association_rules_department_id"), table_name="association_rules")
    op.drop_table("association_rules")
    op.drop_index(op.f("ix_sync_runs_status"), table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_kind"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_cpv_codes_parent_code"), table_name="cpv_codes")
    op.drop_table("cpv_codes")
    op.drop_index(op.f("ix_contractors_tax_id"), table_name="contractors")
    op.drop_table("contractors")

    for enum_name in (
        "contractor_duplicate_status",
        "contract_source",
        "internal_status",
        "contract_phase",
        "change_type",
        "duplicate_status",
        "rule_type",
        "rule_operator",
        "cpv_level",
        "sync_kind",
        "sync_trigger",
        "sync_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
