"""awarding fields

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-12 11:39:40.348251

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("awarding_body", sa.String(length=500), nullable=True))
    op.add_column(
        "contracts", sa.Column("awarding_department", sa.String(length=500), nullable=True)
    )
    op.create_index(
        op.f("ix_contracts_awarding_department"), "contracts", ["awarding_department"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_awarding_department"), table_name="contracts")
    op.drop_column("contracts", "awarding_department")
    op.drop_column("contracts", "awarding_body")
    # ### end Alembic commands ###
